# Generated by Django 4.2 on 2025-07-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_shelf_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='category',
            field=models.CharField(choices=[('business', 'ビジネス'), ('life', '生活'), ('hobby', '趣味'), ('science', '科学'), ('history', '歴史'), ('art', '芸術'), ('novel', '小説'), ('comic', '漫画'), ('other', 'その他')], max_length=100),
        ),
    ]
